### ISSUE TITLE
You can also use → on a result to access Alfred's default File Actions menu not working 

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-repos#14]
If I understand correctly, pressing right arrow here : 

![2017-06-25 at 16 53](https://user-images.githubusercontent.com/6391776/27517112-daf2edd6-59c6-11e7-8466-536acae7079f.png)

Would show me the file actions menu from Alfred. This doesn't work for me. Debugger says nothing too.

**Comment by deanishe** [comment]
It appears to be a bug in Alfred. `type=file` doesn't work if you also set variables.

I'll report it on the forum.

**Comment by deanishe** [comment]
[Bug report](https://www.alfredforum.com/topic/10427-typefile-is-ignored-when-variables-are-also-set/).

**Comment by deanishe** [comment]
Doesn't look like Andrew is going to change Alfred's behaviour. He views `arg` as passed to File Actions and `arg` as passed to downstream objects as two distinct things.

I'll have to back out the changes and revert to the Alfred 2 model to get this working.

**Comment by deanishe** [comment]
Fixed in [v2.1.1](https://github.com/deanishe/alfred-repos/tree/v2.1.1). Enter `repos workflow:update` in Alfred to install the new version.

**Note**: The new version requires Alfred 3.4.1 or newer. Andrew added a new (much cleaner) way to set variables, which lets `type=file` and variables work side-by-side, but the workflow is now incompatible with earlier versions of Alfred 3.

**Comment by nikitavoloboev** [comment]
Sweet. Thank you. 💙

**Comment by deanishe** [comment]
Andrew fixed it, tbh. I mostly just moaned and waited till he did.
